"""Add enterprise knowledge persistence.

Revision ID: 0005_enterprise_knowledge
Revises: 0004_rbac_project_acl
Create Date: 2026-08-12 20:53:07.138671
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

revision: str = "0005_enterprise_knowledge"
down_revision: str | None = "0004_rbac_project_acl"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

INGESTION_ERROR_CODES = (
    "archive_duplicate_path",
    "archive_encrypted",
    "archive_limit_exceeded",
    "archive_nested",
    "archive_path_unsafe",
    "database_unavailable",
    "embedding_dimension_mismatch",
    "embedding_unavailable",
    "encrypted_pdf_unsupported",
    "file_too_large",
    "ingestion_retry_exhausted",
    "lease_lost",
    "no_extractable_text",
    "object_store_unavailable",
    "parser_failed",
    "unsupported_media_type",
    "upload_checksum_mismatch",
    "upload_expired",
    "upload_media_type_mismatch",
    "upload_object_missing",
    "upload_size_mismatch",
)
ERROR_CODE_VALUES_SQL = ",".join(f"'{code}'" for code in INGESTION_ERROR_CODES)


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "embedding_profiles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=True),
        sa.Column(
            "scope_org_id",
            sa.UUID(),
            sa.Computed(
                "COALESCE(org_id, '00000000-0000-0000-0000-000000000000'::uuid)",
                persisted=True,
            ),
            nullable=False,
        ),
        sa.Column("provider_key", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=255), nullable=False),
        sa.Column("dimensions", sa.Integer(), nullable=False),
        sa.Column("distance_metric", sa.String(length=16), server_default="cosine", nullable=False),
        sa.Column(
            "chunking_config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "index_config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="inactive", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "distance_metric IN ('cosine')",
            name=op.f("ck_embedding_profiles_distance_metric_values"),
        ),
        sa.CheckConstraint(
            "status IN ('active','inactive')", name=op.f("ck_embedding_profiles_status_values")
        ),
        sa.CheckConstraint(
            "dimensions > 0", name=op.f("ck_embedding_profiles_positive_dimensions")
        ),
        sa.CheckConstraint(
            "length(provider_key) > 0 AND length(model) > 0 AND length(version) > 0",
            name=op.f("ck_embedding_profiles_nonempty_identity"),
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_embedding_profiles_org_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_embedding_profiles")),
        sa.UniqueConstraint("org_id", "id", name=op.f("uq_embedding_profiles_org_id_id")),
        sa.UniqueConstraint(
            "scope_org_id", "id", name=op.f("uq_embedding_profiles_scope_org_id_id")
        ),
    )
    op.create_index(
        "uq_embedding_profiles_global_active",
        "embedding_profiles",
        ["status"],
        unique=True,
        postgresql_where=sa.text("org_id IS NULL AND status = 'active'"),
    )
    op.create_index(
        "uq_embedding_profiles_global_version",
        "embedding_profiles",
        ["version"],
        unique=True,
        postgresql_where=sa.text("org_id IS NULL"),
    )
    op.create_index(
        "uq_embedding_profiles_org_active",
        "embedding_profiles",
        ["org_id"],
        unique=True,
        postgresql_where=sa.text("org_id IS NOT NULL AND status = 'active'"),
    )
    op.create_index(
        "uq_embedding_profiles_org_version",
        "embedding_profiles",
        ["org_id", "version"],
        unique=True,
        postgresql_where=sa.text("org_id IS NOT NULL"),
    )
    op.execute(
        """
        INSERT INTO embedding_profiles (
          id, org_id, provider_key, model, dimensions, distance_metric,
          chunking_config, index_config, version, status
        ) VALUES (
          '00000000-0000-4000-8000-000000000501', NULL, 'default',
          'text-embedding-v4', 1024, 'cosine',
          '{"maxCodepoints": 1800, "overlapCodepoints": 180}'::jsonb,
          '{"strategy": "exact", "candidateLimit": 50}'::jsonb,
          'default-v1', 'active'
        )
        """
    )
    op.create_table(
        "search_rate_limit_buckets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("subject_type", sa.String(length=16), nullable=False),
        sa.Column("subject_id", sa.UUID(), nullable=False),
        sa.Column("window_started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("window_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("request_count", sa.Integer(), server_default="0", nullable=False),
        sa.CheckConstraint(
            "subject_type IN ('user','organization')",
            name=op.f("ck_search_rate_limit_buckets_subject_type_values"),
        ),
        sa.CheckConstraint(
            "request_count >= 0", name=op.f("ck_search_rate_limit_buckets_nonnegative_count")
        ),
        sa.CheckConstraint(
            "window_expires_at > window_started_at",
            name=op.f("ck_search_rate_limit_buckets_window_order"),
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_search_rate_limit_buckets_org_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_search_rate_limit_buckets")),
        sa.UniqueConstraint(
            "org_id",
            "subject_type",
            "subject_id",
            "window_started_at",
            name="uq_search_rate_limit_buckets_window",
        ),
    )
    op.create_index(
        "ix_search_rate_limit_buckets_expires_at",
        "search_rate_limit_buckets",
        ["window_expires_at"],
        unique=False,
    )
    op.create_table(
        "ingestion_batches",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=32), server_default="pending", nullable=False),
        sa.Column("item_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("ready_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("failed_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(status IN ('completed','completed_with_errors','failed') AND completed_at IS NOT NULL) OR (status IN ('pending','processing') AND completed_at IS NULL)",
            name=op.f("ck_ingestion_batches_completion_state"),
        ),
        sa.CheckConstraint(
            "status IN ('pending','processing','completed','completed_with_errors','failed')",
            name=op.f("ck_ingestion_batches_status_values"),
        ),
        sa.CheckConstraint(
            "item_count >= 0 AND ready_count >= 0 AND failed_count >= 0",
            name=op.f("ck_ingestion_batches_nonnegative_counts"),
        ),
        sa.CheckConstraint(
            "ready_count + failed_count <= item_count",
            name=op.f("ck_ingestion_batches_count_bounds"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_ingestion_batches_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["org_id", "project_id"],
            ["projects.org_id", "projects.id"],
            name=op.f("fk_ingestion_batches_org_id_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_batches")),
        sa.UniqueConstraint(
            "org_id", "project_id", "id", name=op.f("uq_ingestion_batches_org_id_project_id_id")
        ),
    )
    op.create_index(
        "ix_ingestion_batches_org_id_project_id_created_at_id",
        "ingestion_batches",
        ["org_id", "project_id", "created_at", "id"],
        unique=False,
    )
    op.create_table(
        "ingestion_jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("job_kind", sa.String(length=32), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.Column(
            "profile_version", sa.String(length=64), server_default="default-v1", nullable=False
        ),
        sa.Column("status", sa.String(length=16), server_default="queued", nullable=False),
        sa.Column("attempt", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_attempts", sa.Integer(), server_default="5", nullable=False),
        sa.Column(
            "next_attempt_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("lease_owner", sa.String(length=128), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_code", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(status = 'running' AND lease_owner IS NOT NULL AND lease_expires_at IS NOT NULL AND heartbeat_at IS NOT NULL) OR (status <> 'running' AND lease_owner IS NULL AND lease_expires_at IS NULL AND heartbeat_at IS NULL)",
            name=op.f("ck_ingestion_jobs_lease_state"),
        ),
        sa.CheckConstraint(
            "status <> 'running' OR lease_expires_at > heartbeat_at",
            name=op.f("ck_ingestion_jobs_lease_order"),
        ),
        sa.CheckConstraint(
            "(status IN ('completed','failed') AND completed_at IS NOT NULL) OR (status IN ('queued','running') AND completed_at IS NULL)",
            name=op.f("ck_ingestion_jobs_completion_state"),
        ),
        sa.CheckConstraint(
            "job_kind IN ('expand_archive','index_resource_version')",
            name=op.f("ck_ingestion_jobs_kind_values"),
        ),
        sa.CheckConstraint(
            "status IN ('queued','running','completed','failed')",
            name=op.f("ck_ingestion_jobs_status_values"),
        ),
        sa.CheckConstraint(
            "max_attempts > 0 AND attempt >= 0 AND attempt <= max_attempts",
            name=op.f("ck_ingestion_jobs_attempt_bounds"),
        ),
        sa.CheckConstraint(
            f"last_error_code IS NULL OR last_error_code IN ({ERROR_CODE_VALUES_SQL})",
            name=op.f("ck_ingestion_jobs_error_code_values"),
        ),
        sa.ForeignKeyConstraint(
            ["org_id", "project_id"],
            ["projects.org_id", "projects.id"],
            name=op.f("fk_ingestion_jobs_org_id_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_jobs")),
        sa.UniqueConstraint(
            "job_kind", "target_id", "profile_version", name="uq_ingestion_jobs_kind_target_profile"
        ),
        sa.UniqueConstraint(
            "org_id", "project_id", "id", name=op.f("uq_ingestion_jobs_org_id_project_id_id")
        ),
    )
    op.create_index(
        "ix_ingestion_jobs_claim",
        "ingestion_jobs",
        ["status", "next_attempt_at", "created_at", "id"],
        unique=False,
    )
    op.create_index(
        "ix_ingestion_jobs_org_id_project_id_target_id",
        "ingestion_jobs",
        ["org_id", "project_id", "target_id"],
        unique=False,
    )
    op.create_table(
        "knowledge_resources",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("source_type", sa.String(length=24), nullable=False),
        sa.Column("source_id", sa.String(length=255), nullable=False),
        sa.Column("external_id", sa.String(length=1024), nullable=False),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_version_id", sa.UUID(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.Column("purged_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "source_type IN ('upload','zip_entry','feishu','tencent_docs')",
            name=op.f("ck_knowledge_resources_source_type_values"),
        ),
        sa.CheckConstraint(
            "(deleted_at IS NULL AND deleted_by IS NULL) OR (deleted_at IS NOT NULL AND deleted_by IS NOT NULL)",
            name=op.f("ck_knowledge_resources_deletion_actor"),
        ),
        sa.CheckConstraint(
            "length(source_id) > 0 AND length(external_id) > 0",
            name=op.f("ck_knowledge_resources_source_identity"),
        ),
        sa.CheckConstraint("length(title) > 0", name=op.f("ck_knowledge_resources_nonempty_title")),
        sa.CheckConstraint(
            "purged_at IS NULL OR (deleted_at IS NOT NULL AND purged_at >= deleted_at)",
            name=op.f("ck_knowledge_resources_purge_order"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_knowledge_resources_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"], ["users.id"], name=op.f("fk_knowledge_resources_deleted_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["org_id", "project_id"],
            ["projects.org_id", "projects.id"],
            name=op.f("fk_knowledge_resources_org_id_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_resources")),
        sa.UniqueConstraint(
            "org_id", "project_id", "id", name=op.f("uq_knowledge_resources_org_id_project_id_id")
        ),
    )
    op.create_index(
        "ix_knowledge_resources_org_id_project_id_created_at_id",
        "knowledge_resources",
        ["org_id", "project_id", "created_at", "id"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "uq_knowledge_resources_active_source",
        "knowledge_resources",
        ["org_id", "project_id", "source_type", "source_id", "external_id"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "ingestion_job_attempts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("trigger", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="queued", nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("safe_detail", sa.Text(), nullable=True),
        sa.Column(
            "queued_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(status = 'queued' AND started_at IS NULL AND completed_at IS NULL AND error_code IS NULL) OR (status = 'running' AND started_at IS NOT NULL AND completed_at IS NULL AND error_code IS NULL) OR (status = 'succeeded' AND started_at IS NOT NULL AND completed_at IS NOT NULL AND error_code IS NULL) OR (status = 'failed' AND started_at IS NOT NULL AND completed_at IS NOT NULL AND error_code IS NOT NULL)",
            name=op.f("ck_ingestion_job_attempts_result_state"),
        ),
        sa.CheckConstraint(
            "started_at IS NULL OR started_at >= queued_at",
            name=op.f("ck_ingestion_job_attempts_start_order"),
        ),
        sa.CheckConstraint(
            "completed_at IS NULL OR (started_at IS NOT NULL AND completed_at >= started_at)",
            name=op.f("ck_ingestion_job_attempts_completion_order"),
        ),
        sa.CheckConstraint(
            f"error_code IS NULL OR error_code IN ({ERROR_CODE_VALUES_SQL})",
            name=op.f("ck_ingestion_job_attempts_error_code_values"),
        ),
        sa.CheckConstraint(
            "status IN ('queued','running','succeeded','failed')",
            name=op.f("ck_ingestion_job_attempts_status_values"),
        ),
        sa.CheckConstraint(
            "trigger IN ('automatic','manual')",
            name=op.f("ck_ingestion_job_attempts_trigger_values"),
        ),
        sa.CheckConstraint("ordinal > 0", name=op.f("ck_ingestion_job_attempts_positive_ordinal")),
        sa.ForeignKeyConstraint(
            ["org_id", "project_id", "job_id"],
            ["ingestion_jobs.org_id", "ingestion_jobs.project_id", "ingestion_jobs.id"],
            name=op.f("fk_ingestion_job_attempts_org_id_project_id_job_id_ingestion_jobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_job_attempts")),
        sa.UniqueConstraint("job_id", "ordinal", name="uq_ingestion_job_attempts_job_ordinal"),
        sa.UniqueConstraint(
            "org_id",
            "project_id",
            "id",
            name=op.f("uq_ingestion_job_attempts_org_id_project_id_id"),
        ),
    )
    op.create_index(
        "ix_ingestion_job_attempts_org_id_project_id_job_id_ordinal",
        "ingestion_job_attempts",
        ["org_id", "project_id", "job_id", "ordinal"],
        unique=False,
    )
    op.execute(
        """
        CREATE FUNCTION cairn_preserve_ingestion_job_attempt_history()
        RETURNS trigger
        LANGUAGE plpgsql
        SET search_path = pg_catalog, public
        AS $$
        BEGIN
          IF TG_OP = 'DELETE' THEN
            IF pg_trigger_depth() > 1 THEN
              RETURN OLD;
            END IF;

            RAISE EXCEPTION 'ingestion job attempt history cannot be deleted directly'
              USING
                ERRCODE = 'integrity_constraint_violation',
                CONSTRAINT = 'ingestion_job_attempts_immutable_history';
          END IF;

          IF OLD.status IN ('succeeded', 'failed') THEN
            RAISE EXCEPTION 'terminal ingestion job attempt history cannot be updated'
              USING
                ERRCODE = 'integrity_constraint_violation',
                CONSTRAINT = 'ingestion_job_attempts_immutable_history';
          END IF;

          IF (NEW.id, NEW.org_id, NEW.project_id, NEW.job_id, NEW.ordinal,
              NEW.trigger, NEW.queued_at)
             IS DISTINCT FROM
             (OLD.id, OLD.org_id, OLD.project_id, OLD.job_id, OLD.ordinal,
              OLD.trigger, OLD.queued_at) THEN
            RAISE EXCEPTION 'ingestion job attempt identity cannot be updated'
              USING
                ERRCODE = 'integrity_constraint_violation',
                CONSTRAINT = 'ingestion_job_attempts_immutable_history';
          END IF;

          IF NOT (
            (OLD.status = 'queued' AND NEW.status IN ('queued', 'running'))
            OR
            (OLD.status = 'running' AND NEW.status IN ('running', 'succeeded', 'failed'))
          ) THEN
            RAISE EXCEPTION 'invalid ingestion job attempt status transition'
              USING
                ERRCODE = 'integrity_constraint_violation',
                CONSTRAINT = 'ingestion_job_attempts_status_transition';
          END IF;

          IF OLD.started_at IS NOT NULL
             AND NEW.started_at IS DISTINCT FROM OLD.started_at THEN
            RAISE EXCEPTION 'ingestion job attempt start time cannot be updated'
              USING
                ERRCODE = 'integrity_constraint_violation',
                CONSTRAINT = 'ingestion_job_attempts_immutable_history';
          END IF;

          RETURN NEW;
        END
        $$;

        CREATE TRIGGER trg_ingestion_job_attempts_preserve_history
        BEFORE UPDATE OR DELETE ON public.ingestion_job_attempts
        FOR EACH ROW
        EXECUTE FUNCTION cairn_preserve_ingestion_job_attempt_history();
        """
    )
    op.create_table(
        "knowledge_resource_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("resource_id", sa.UUID(), nullable=False),
        sa.Column("source_type", sa.String(length=24), nullable=False),
        sa.Column("source_id", sa.String(length=255), nullable=False),
        sa.Column("external_id", sa.String(length=1024), nullable=False),
        sa.Column("source_version", sa.String(length=255), nullable=False),
        sa.Column("object_key", sa.String(length=1024), nullable=False),
        sa.Column("media_type", sa.String(length=127), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("parser_profile", sa.String(length=64), nullable=False),
        sa.Column("chunking_profile", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="queued", nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("processing_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ready_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(status = 'ready' AND error_code IS NULL AND ready_at IS NOT NULL) OR (status = 'failed' AND error_code IS NOT NULL AND ready_at IS NULL) OR (status IN ('queued','processing') AND error_code IS NULL AND ready_at IS NULL)",
            name=op.f("ck_knowledge_resource_versions_result_state"),
        ),
        sa.CheckConstraint(
            f"error_code IS NULL OR error_code IN ({ERROR_CODE_VALUES_SQL})",
            name=op.f("ck_knowledge_resource_versions_error_code_values"),
        ),
        sa.CheckConstraint(
            "sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_knowledge_resource_versions_sha256_format")
        ),
        sa.CheckConstraint(
            "source_type IN ('upload','zip_entry','feishu','tencent_docs')",
            name=op.f("ck_knowledge_resource_versions_source_type_values"),
        ),
        sa.CheckConstraint(
            "status IN ('queued','processing','ready','failed')",
            name=op.f("ck_knowledge_resource_versions_status_values"),
        ),
        sa.CheckConstraint(
            "processing_started_at IS NULL OR processing_started_at >= created_at",
            name=op.f("ck_knowledge_resource_versions_processing_order"),
        ),
        sa.CheckConstraint(
            "ready_at IS NULL OR "
            "(processing_started_at IS NOT NULL AND ready_at >= processing_started_at)",
            name=op.f("ck_knowledge_resource_versions_ready_order"),
        ),
        sa.CheckConstraint(
            "size_bytes > 0", name=op.f("ck_knowledge_resource_versions_positive_size")
        ),
        sa.ForeignKeyConstraint(
            ["org_id", "project_id", "resource_id"],
            [
                "knowledge_resources.org_id",
                "knowledge_resources.project_id",
                "knowledge_resources.id",
            ],
            name=op.f(
                "fk_knowledge_resource_versions_org_id_project_id_resource_id_knowledge_resources"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_resource_versions")),
        sa.UniqueConstraint("object_key", name=op.f("uq_knowledge_resource_versions_object_key")),
        sa.UniqueConstraint(
            "org_id",
            "project_id",
            "id",
            name=op.f("uq_knowledge_resource_versions_org_id_project_id_id"),
        ),
        sa.UniqueConstraint(
            "org_id",
            "project_id",
            "resource_id",
            "id",
            name=op.f("uq_knowledge_resource_versions_org_id_project_id_resource_id_id"),
        ),
        sa.UniqueConstraint(
            "org_id",
            "source_type",
            "source_id",
            "external_id",
            "source_version",
            name="uq_knowledge_resource_versions_source_version",
        ),
    )
    op.create_index(
        "ix_knowledge_versions_project_resource_created",
        "knowledge_resource_versions",
        ["org_id", "project_id", "resource_id", "created_at", "id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_knowledge_resources_current_version",
        "knowledge_resources",
        "knowledge_resource_versions",
        ["org_id", "project_id", "id", "current_version_id"],
        ["org_id", "project_id", "resource_id", "id"],
    )
    op.create_table(
        "ingestion_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("batch_id", sa.UUID(), nullable=False),
        sa.Column("parent_item_id", sa.UUID(), nullable=True),
        sa.Column("normalized_path", sa.String(length=1024), nullable=False),
        sa.Column("media_type", sa.String(length=127), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=24), server_default="awaiting_upload", nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.Column("resource_id", sa.UUID(), nullable=True),
        sa.Column("resource_version_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(status = 'failed' AND error_code IS NOT NULL AND completed_at IS NOT NULL) OR (status = 'ready' AND error_code IS NULL AND completed_at IS NOT NULL) OR (status IN ('awaiting_upload','queued','processing') AND error_code IS NULL AND completed_at IS NULL)",
            name=op.f("ck_ingestion_items_result_state"),
        ),
        sa.CheckConstraint(
            f"error_code IS NULL OR error_code IN ({ERROR_CODE_VALUES_SQL})",
            name=op.f("ck_ingestion_items_error_code_values"),
        ),
        sa.CheckConstraint(
            "sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_ingestion_items_sha256_format")
        ),
        sa.CheckConstraint(
            "status IN ('awaiting_upload','queued','processing','ready','failed')",
            name=op.f("ck_ingestion_items_status_values"),
        ),
        sa.CheckConstraint(
            "length(normalized_path) > 0", name=op.f("ck_ingestion_items_nonempty_path")
        ),
        sa.CheckConstraint("size_bytes > 0", name=op.f("ck_ingestion_items_positive_size")),
        sa.ForeignKeyConstraint(
            ["org_id", "project_id", "batch_id"],
            ["ingestion_batches.org_id", "ingestion_batches.project_id", "ingestion_batches.id"],
            name=op.f("fk_ingestion_items_org_id_project_id_batch_id_ingestion_batches"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id", "project_id", "parent_item_id"],
            ["ingestion_items.org_id", "ingestion_items.project_id", "ingestion_items.id"],
            name=op.f("fk_ingestion_items_org_id_project_id_parent_item_id_ingestion_items"),
        ),
        sa.ForeignKeyConstraint(
            ["org_id", "project_id", "resource_id", "resource_version_id"],
            [
                "knowledge_resource_versions.org_id",
                "knowledge_resource_versions.project_id",
                "knowledge_resource_versions.resource_id",
                "knowledge_resource_versions.id",
            ],
            name=op.f(
                "fk_ingestion_items_org_id_project_id_resource_id_resource_version_id_knowledge_resource_versions"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["org_id", "project_id", "resource_id"],
            [
                "knowledge_resources.org_id",
                "knowledge_resources.project_id",
                "knowledge_resources.id",
            ],
            name=op.f("fk_ingestion_items_org_id_project_id_resource_id_knowledge_resources"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_items")),
        sa.UniqueConstraint(
            "org_id", "project_id", "id", name=op.f("uq_ingestion_items_org_id_project_id_id")
        ),
    )
    op.create_index(
        "ix_ingestion_items_org_id_project_id_batch_id_status_id",
        "ingestion_items",
        ["org_id", "project_id", "batch_id", "status", "id"],
        unique=False,
    )
    op.create_index(
        "uq_ingestion_items_batch_parent_path",
        "ingestion_items",
        [
            "org_id",
            "project_id",
            "batch_id",
            sa.literal_column(
                "COALESCE(parent_item_id, '00000000-0000-0000-0000-000000000000'::uuid)"
            ),
            "normalized_path",
        ],
        unique=True,
    )
    op.execute(
        """
        CREATE FUNCTION cairn_derive_ingestion_batch_summary()
        RETURNS trigger
        LANGUAGE plpgsql
        SET search_path = pg_catalog, public
        AS $$
        DECLARE
          total_count integer;
          ready_total integer;
          failed_total integer;
          has_started boolean;
          derived_status text;
        BEGIN
          SELECT
            count(*)::integer,
            count(*) FILTER (WHERE status = 'ready')::integer,
            count(*) FILTER (WHERE status = 'failed')::integer,
            COALESCE(bool_or(status <> 'awaiting_upload'), false)
          INTO total_count, ready_total, failed_total, has_started
          FROM public.ingestion_items
          WHERE org_id = NEW.org_id
            AND project_id = NEW.project_id
            AND batch_id = NEW.id;

          IF total_count = 0 OR NOT has_started THEN
            derived_status := 'pending';
          ELSIF ready_total = total_count THEN
            derived_status := 'completed';
          ELSIF failed_total = total_count THEN
            derived_status := 'failed';
          ELSIF ready_total + failed_total = total_count THEN
            derived_status := 'completed_with_errors';
          ELSE
            derived_status := 'processing';
          END IF;

          NEW.item_count := total_count;
          NEW.ready_count := ready_total;
          NEW.failed_count := failed_total;
          NEW.status := derived_status;

          IF derived_status IN ('completed', 'completed_with_errors', 'failed') THEN
            IF TG_OP = 'UPDATE'
               AND OLD.status = derived_status
               AND OLD.completed_at IS NOT NULL THEN
              NEW.completed_at := OLD.completed_at;
            ELSE
              NEW.completed_at := transaction_timestamp();
            END IF;
          ELSE
            NEW.completed_at := NULL;
          END IF;

          RETURN NEW;
        END
        $$;

        CREATE TRIGGER trg_ingestion_batches_derive_summary
        BEFORE INSERT OR UPDATE ON public.ingestion_batches
        FOR EACH ROW
        EXECUTE FUNCTION cairn_derive_ingestion_batch_summary();

        CREATE FUNCTION cairn_refresh_ingestion_batch_from_item()
        RETURNS trigger
        LANGUAGE plpgsql
        SET search_path = pg_catalog, public
        AS $$
        BEGIN
          IF TG_OP IN ('DELETE', 'UPDATE') THEN
            UPDATE public.ingestion_batches
            SET status = status
            WHERE org_id = OLD.org_id
              AND project_id = OLD.project_id
              AND id = OLD.batch_id;
          END IF;

          IF TG_OP = 'INSERT'
             OR (
               TG_OP = 'UPDATE'
               AND (NEW.org_id, NEW.project_id, NEW.batch_id)
                   IS DISTINCT FROM (OLD.org_id, OLD.project_id, OLD.batch_id)
             ) THEN
            UPDATE public.ingestion_batches
            SET status = status
            WHERE org_id = NEW.org_id
              AND project_id = NEW.project_id
              AND id = NEW.batch_id;
          END IF;

          RETURN NULL;
        END
        $$;

        CREATE TRIGGER trg_ingestion_items_refresh_batch
        AFTER INSERT OR UPDATE OR DELETE ON public.ingestion_items
        FOR EACH ROW
        EXECUTE FUNCTION cairn_refresh_ingestion_batch_from_item();
        """
    )
    op.create_table(
        "knowledge_chunks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("resource_id", sa.UUID(), nullable=False),
        sa.Column("resource_version_id", sa.UUID(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("normalized_text", sa.Text(), nullable=False),
        sa.Column("locator", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('simple'::regconfig, normalized_text)", persisted=True),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(text) > 0 AND length(normalized_text) > 0",
            name=op.f("ck_knowledge_chunks_nonempty_text"),
        ),
        sa.CheckConstraint("ordinal >= 0", name=op.f("ck_knowledge_chunks_nonnegative_ordinal")),
        sa.ForeignKeyConstraint(
            ["org_id", "project_id", "resource_id", "resource_version_id"],
            [
                "knowledge_resource_versions.org_id",
                "knowledge_resource_versions.project_id",
                "knowledge_resource_versions.resource_id",
                "knowledge_resource_versions.id",
            ],
            name=op.f(
                "fk_knowledge_chunks_org_id_project_id_resource_id_resource_version_id_knowledge_resource_versions"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_chunks")),
        sa.UniqueConstraint(
            "org_id",
            "project_id",
            "resource_id",
            "resource_version_id",
            "id",
            name=op.f("uq_knowledge_chunks_org_id_project_id_resource_id_resource_version_id_id"),
        ),
        sa.UniqueConstraint(
            "resource_version_id", "ordinal", name="uq_knowledge_chunks_version_ordinal"
        ),
    )
    op.create_index(
        "ix_knowledge_chunks_normalized_text_trgm",
        "knowledge_chunks",
        ["normalized_text"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"normalized_text": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_knowledge_chunks_project_version_ordinal",
        "knowledge_chunks",
        ["org_id", "project_id", "resource_version_id", "ordinal"],
        unique=False,
    )
    op.create_index(
        "ix_knowledge_chunks_search_vector",
        "knowledge_chunks",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_table(
        "chunk_embeddings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("resource_id", sa.UUID(), nullable=False),
        sa.Column("resource_version_id", sa.UUID(), nullable=False),
        sa.Column("chunk_id", sa.UUID(), nullable=False),
        sa.Column("embedding_profile_scope_org_id", sa.UUID(), nullable=False),
        sa.Column("embedding_profile_id", sa.UUID(), nullable=False),
        sa.Column("embedding", Vector(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "embedding_profile_scope_org_id = org_id OR "
            "embedding_profile_scope_org_id = "
            "'00000000-0000-0000-0000-000000000000'::uuid",
            name=op.f("ck_chunk_embeddings_profile_scope_values"),
        ),
        sa.ForeignKeyConstraint(
            ["embedding_profile_scope_org_id", "embedding_profile_id"],
            ["embedding_profiles.scope_org_id", "embedding_profiles.id"],
            name=op.f(
                "fk_chunk_embeddings_embedding_profile_scope_org_id_embedding_profile_id_embedding_profiles"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id", "project_id", "resource_id", "resource_version_id", "chunk_id"],
            [
                "knowledge_chunks.org_id",
                "knowledge_chunks.project_id",
                "knowledge_chunks.resource_id",
                "knowledge_chunks.resource_version_id",
                "knowledge_chunks.id",
            ],
            name=op.f(
                "fk_chunk_embeddings_org_id_project_id_resource_id_resource_version_id_chunk_id_knowledge_chunks"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chunk_embeddings")),
        sa.UniqueConstraint(
            "chunk_id", "embedding_profile_id", name="uq_chunk_embeddings_chunk_profile"
        ),
    )
    op.create_index(
        "ix_chunk_embeddings_org_id_project_id_profile_id",
        "chunk_embeddings",
        ["org_id", "project_id", "embedding_profile_id"],
        unique=False,
    )
    op.create_table(
        "upload_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("batch_id", sa.UUID(), nullable=False),
        sa.Column("item_id", sa.UUID(), nullable=False),
        sa.Column("original_file_name", sa.String(length=255), nullable=False),
        sa.Column("declared_media_type", sa.String(length=127), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("object_key", sa.String(length=1024), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("abandoned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resource_version_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_upload_sessions_sha256_format")
        ),
        sa.CheckConstraint(
            "NOT (completed_at IS NOT NULL AND abandoned_at IS NOT NULL)",
            name=op.f("ck_upload_sessions_completion_state"),
        ),
        sa.CheckConstraint("expires_at > created_at", name=op.f("ck_upload_sessions_expiry_order")),
        sa.CheckConstraint("size_bytes > 0", name=op.f("ck_upload_sessions_positive_size")),
        sa.ForeignKeyConstraint(
            ["org_id", "project_id", "batch_id"],
            ["ingestion_batches.org_id", "ingestion_batches.project_id", "ingestion_batches.id"],
            name=op.f("fk_upload_sessions_org_id_project_id_batch_id_ingestion_batches"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id", "project_id", "item_id"],
            ["ingestion_items.org_id", "ingestion_items.project_id", "ingestion_items.id"],
            name=op.f("fk_upload_sessions_org_id_project_id_item_id_ingestion_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id", "project_id", "resource_version_id"],
            [
                "knowledge_resource_versions.org_id",
                "knowledge_resource_versions.project_id",
                "knowledge_resource_versions.id",
            ],
            name=op.f(
                "fk_upload_sessions_org_id_project_id_resource_version_id_knowledge_resource_versions"
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_upload_sessions")),
        sa.UniqueConstraint("object_key", name=op.f("uq_upload_sessions_object_key")),
        sa.UniqueConstraint(
            "org_id", "project_id", "id", name=op.f("uq_upload_sessions_org_id_project_id_id")
        ),
        sa.UniqueConstraint(
            "org_id",
            "project_id",
            "item_id",
            name=op.f("uq_upload_sessions_org_id_project_id_item_id"),
        ),
    )
    op.create_index(
        "ix_upload_sessions_org_id_project_id_expires_at_id",
        "upload_sessions",
        ["org_id", "project_id", "expires_at", "id"],
        unique=False,
        postgresql_where=sa.text("completed_at IS NULL AND abandoned_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "DROP TRIGGER IF EXISTS trg_ingestion_job_attempts_preserve_history "
        "ON ingestion_job_attempts"
    )
    op.execute("DROP FUNCTION IF EXISTS cairn_preserve_ingestion_job_attempt_history()")
    op.execute("DROP TRIGGER IF EXISTS trg_ingestion_items_refresh_batch ON ingestion_items")
    op.execute("DROP FUNCTION IF EXISTS cairn_refresh_ingestion_batch_from_item()")
    op.execute("DROP TRIGGER IF EXISTS trg_ingestion_batches_derive_summary ON ingestion_batches")
    op.execute("DROP FUNCTION IF EXISTS cairn_derive_ingestion_batch_summary()")
    op.drop_index(
        "ix_upload_sessions_org_id_project_id_expires_at_id",
        table_name="upload_sessions",
        postgresql_where=sa.text("completed_at IS NULL AND abandoned_at IS NULL"),
    )
    op.drop_table("upload_sessions")
    op.drop_index("ix_chunk_embeddings_org_id_project_id_profile_id", table_name="chunk_embeddings")
    op.drop_table("chunk_embeddings")
    op.drop_index(
        "ix_knowledge_chunks_search_vector", table_name="knowledge_chunks", postgresql_using="gin"
    )
    op.drop_index("ix_knowledge_chunks_project_version_ordinal", table_name="knowledge_chunks")
    op.drop_index(
        "ix_knowledge_chunks_normalized_text_trgm",
        table_name="knowledge_chunks",
        postgresql_using="gin",
        postgresql_ops={"normalized_text": "gin_trgm_ops"},
    )
    op.drop_table("knowledge_chunks")
    op.drop_index("uq_ingestion_items_batch_parent_path", table_name="ingestion_items")
    op.drop_index(
        "ix_ingestion_items_org_id_project_id_batch_id_status_id", table_name="ingestion_items"
    )
    op.drop_table("ingestion_items")
    op.drop_constraint(
        "fk_knowledge_resources_current_version",
        "knowledge_resources",
        type_="foreignkey",
    )
    op.drop_index(
        "ix_knowledge_versions_project_resource_created", table_name="knowledge_resource_versions"
    )
    op.drop_table("knowledge_resource_versions")
    op.drop_index(
        "ix_ingestion_job_attempts_org_id_project_id_job_id_ordinal",
        table_name="ingestion_job_attempts",
    )
    op.drop_table("ingestion_job_attempts")
    op.drop_index(
        "uq_knowledge_resources_active_source",
        table_name="knowledge_resources",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(
        "ix_knowledge_resources_org_id_project_id_created_at_id",
        table_name="knowledge_resources",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("knowledge_resources")
    op.drop_index("ix_ingestion_jobs_org_id_project_id_target_id", table_name="ingestion_jobs")
    op.drop_index("ix_ingestion_jobs_claim", table_name="ingestion_jobs")
    op.drop_table("ingestion_jobs")
    op.drop_index(
        "ix_ingestion_batches_org_id_project_id_created_at_id", table_name="ingestion_batches"
    )
    op.drop_table("ingestion_batches")
    op.drop_index("ix_search_rate_limit_buckets_expires_at", table_name="search_rate_limit_buckets")
    op.drop_table("search_rate_limit_buckets")
    op.drop_index(
        "uq_embedding_profiles_org_version",
        table_name="embedding_profiles",
        postgresql_where=sa.text("org_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_embedding_profiles_org_active",
        table_name="embedding_profiles",
        postgresql_where=sa.text("org_id IS NOT NULL AND status = 'active'"),
    )
    op.drop_index(
        "uq_embedding_profiles_global_version",
        table_name="embedding_profiles",
        postgresql_where=sa.text("org_id IS NULL"),
    )
    op.drop_index(
        "uq_embedding_profiles_global_active",
        table_name="embedding_profiles",
        postgresql_where=sa.text("org_id IS NULL AND status = 'active'"),
    )
    op.drop_table("embedding_profiles")
    # ### end Alembic commands ###
    op.execute(
        """
        DO $$ BEGIN
          DROP EXTENSION IF EXISTS pg_trgm;
        EXCEPTION WHEN dependent_objects_still_exist THEN NULL;
        END $$
        """
    )
    op.execute(
        """
        DO $$ BEGIN
          DROP EXTENSION IF EXISTS vector;
        EXCEPTION WHEN dependent_objects_still_exist THEN NULL;
        END $$
        """
    )
